<a href="https://colab.research.google.com/github/harsh24895/pyTorch/blob/main/FundamentalOfTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("ejes")



ejes


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


#introduction to tensors
Creating Tensor

In [ ]:
import torch
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt



print(torch.__version__)

#Scalar
scalar = torch.tensor(7)
scalar

2.3.1+cu121


tensor(7)

Pytorch tensors are created using torch.Tensor()

In [ ]:
import torch
#Scalar
scalar = torch.tensor(7);
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get the tensor as an int value
scalar.item()

7

In [ ]:
#vector
import torch
vector = torch.tensor([1, 1])
vector

tensor([1, 1])

In [ ]:
#vector dimension
vector.ndim

1

In [ ]:
#vector for shape
vector.shape

torch.Size([2])

In [ ]:
#MATRIX all the things are call with the torch.tensor even vector, scalar and Matrix

MATRIX  = torch.tensor([[1,3],
                        [9,4]])
MATRIX

tensor([[1, 3],
        [9, 4]])

In [ ]:
#shape of matrix
MATRIX.shape


torch.Size([2, 2])

In [ ]:
#matrix dimension
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 3])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [ ]:
TENSOR.shape
#here the 1 is from the whole index []
# second 3 is from the three index
#third 3 is from the 3 input in the index[]

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR = torch.tensor([[[[1,2,3],[2,3,4],[3,4,5]]]])
TENSOR.shape

torch.Size([1, 1, 3, 3])

#Random Tensors

In [ ]:
#Create a random tensor of size (2,4)
random_Tensor = torch.rand(2,4)
random_Tensor

tensor([[0.6582, 0.8077, 0.0390, 0.0096],
        [0.6103, 0.9099, 0.2739, 0.7631]])

In [ ]:
random_Tensor.ndim

2

In [ ]:
random_Tensor.shape

torch.Size([2, 4])

Create a random tensor with similar shape to an image  tensor

In [ ]:
random_image_size = torch.rand(size=(244,244,5)) #height, width, colour channels(R,G,B)
#also colour channels will switch first or last in the index().


random_image_size.shape , random_image_size.ndim

(torch.Size([244, 244, 5]), 3)

#Zero and ones

In [ ]:
import torch
#Create a tensor of all zeros
zero = torch.zeros(size=(2,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# tensor of ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype # this the default data type

torch.float32

In [ ]:
zero.dtype #expizitlity define the dataType

torch.float32

#Creating a range of Tensors and Tensors-like

In [ ]:
import torch
#use torch.range()
tt = torch.arange(0,5) #use the arange() instead of range() as the range is been in consistant in the python
tt

tensor([0, 1, 2, 3, 4])

In [ ]:
#Creating tensors zeros like
tenZeros = torch.zeros_like(tt)
tenZeros

tensor([0, 0, 0, 0, 0])

#TensoDataType

Note: We gonna get more error in datatypes with pytorch and deep learning
1. tensor not right datatype
2. tensor not right shape
3. tensor not right device

In [ ]:
#Float Datatype
float_t = torch.tensor([5.0,6.0,8.0],
                       dtype=None,# datatype that you can set in the tensor(ex: float32 or float16 or float64)
                       device=None, #  the default CPU and we can change to GPU(cuda)
                       requires_grad=False)# whether or not to track gradients with this tensors operations

float_t


tensor([5., 6., 8.])

In [ ]:
float_t.dtype

torch.float32

In [ ]:
#Convert the datatype to float32 default to float 16
float_16 = float_t.type(torch.float16)
float_16

tensor([5., 6., 8.], dtype=torch.float16)

In [ ]:
#even we can multiply the tensor
float_16*float_t

tensor([25., 36., 64.])

In [ ]:
#int32 to float multiply
int_32_tensor = torch.tensor([6,9,8], dtype=torch.int32)
int_32_tensor

tensor([6, 9, 8], dtype=torch.int32)

In [ ]:
int_32_tensor*float_16

tensor([30., 54., 64.], dtype=torch.float16)

#Getting information from the tensor
1.tensor not right datatype #to get the tensor information use tensor.dtype
2.tensor not right shape #to get the tensor information use tensor.shape
3.tensor not right device #to get the tensor information use tensor.device

In [ ]:
some = torch.rand(3,5)
some

tensor([[0.3140, 0.7058, 0.3973, 0.9919, 0.7966],
        [0.3987, 0.2855, 0.3789, 0.3765, 0.9320],
        [0.5554, 0.8759, 0.2949, 0.6332, 0.5490]])

In [ ]:
some.size(),  #this need to be in () if we need to call the size() menthod
some.shape #this doesn't required the () as this has a attribute

torch.Size([3, 5])

In [ ]:
#find the details of some tensor
print(some)
print(f"Datatype of tensor:{some.dtype}")
print(f"Shape of the tensor:{some.shape}")
print(f"Device od the tensor:{some.device}")

tensor([[0.3140, 0.7058, 0.3973, 0.9919, 0.7966],
        [0.3987, 0.2855, 0.3789, 0.3765, 0.9320],
        [0.5554, 0.8759, 0.2949, 0.6332, 0.5490]])
Datatype of tensor:torch.float32
Shape of the tensor:torch.Size([3, 5])
Device od the tensor:cpu


In [ ]:
#manipulating the tensors add, sub, multi, division
import torch
tensor = torch.tensor([4,5,6])
tensor +5

tensor([ 9, 10, 11])

In [ ]:
tensor -10

tensor([-6, -5, -4])

In [ ]:
#Using the inbuilt function in the tensor

torch.add(tensor,10)

tensor([14, 15, 16])

In [ ]:
#sub using inbuilt function
torch.sub(tensor,5)

tensor([-1,  0,  1])

#Matrix multiplication

Note: we can use the @ or matmul for the multiplication

#Make sure the two rules 1. inner dimmensions should match
ex: 1. (4,2) @(4,2) this will throw the error as the inner dimension is not mathcing
2. (4,2)@(2,4) this will work as their inner dimension matches
3.(2,4)@(4,2)this will work too

#2. the matrix has  the shape of outer dimension
1.(2,3)@(3,2) it will work and shows (2,2)

2.(4,5)@(5,4) - >(4,4)

In [ ]:
#Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals:{tensor * tensor}")

tensor([4, 5, 6]) * tensor([4, 5, 6])
Equals:tensor([16, 25, 36])


In [ ]:
#matix multiplication

torch.matmul(tensor, tensor) #vector version instead of for loop

tensor(77)

In [ ]:
#how it works with multiplication
4*4+5*5+6*6


77

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor(77)
CPU times: user 1.7 ms, sys: 1 ms, total: 2.7 ms
Wall time: 20.7 ms


In [ ]:
#another way to multipy the tensor
tensor @ tensor


tensor(77)

In [ ]:
#shapes of matrix multiplication

tensor1 = torch.tensor([[2,5],
                       [3,6],
                       [5,4]])

tensor2 = torch.tensor([[5,4],
                       [7,2],
                       [8,9]])

torch.mm(tensor1,tensor2)#.mm stands for matmul mm is a short form of matmul



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

# to fix the tensor we will use transpose using the T.


In [ ]:
tensor2.shape

torch.Size([3, 2])

In [ ]:
#here is the ex using the T
tensor2.T, tensor2.T.shape

(tensor([[5, 7, 8],
         [4, 2, 9]]),
 torch.Size([2, 3]))

In [ ]:
# now using tensor2.T we will multipy the matrix
# as we transform tensor2.T not the tensor1. This is eligible with the rule 1
# rule 1 is inner dimension should match so for our examples
# the tensor 1 has dimension of (3,2) and we transpose the tensor2 to (2,3) so this will work without any issue

torch.mm(tensor1,tensor2.T)#.mm stands for matmul mm is a short form of matmul



tensor([[30, 24, 61],
        [39, 33, 78],
        [41, 43, 76]])

In [ ]:
# here we are doing the outer dimmension example
# we will set the (4,3)matrix to match with rule 2
tensor3 = torch.tensor([[5,6,5],
                       [4,5,7],
                       [0,0,8],
                        [2,5,8]])
tensor4 = torch.tensor([[3,6,2],
                       [1,1,1],
                       [3,8,4],
                        [4,7,8]])

In [ ]:
torch.mm(tensor3, tensor4)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [ ]:
tensor3.T

tensor([[5, 4, 0, 2],
        [6, 5, 0, 5],
        [5, 7, 8, 8]])

In [ ]:
tensor3.T.shape

torch.Size([3, 4])

In [ ]:
torch.mm(tensor3.T, tensor4)

tensor([[ 27,  48,  30],
        [ 43,  76,  57],
        [ 78, 157, 113]])

#Finding the min,max,sum(tesnor aggregation)

In [ ]:
#Create a tensor
a = torch.arange(1,50,10)
a

tensor([ 1, 11, 21, 31, 41])

In [ ]:
torch.min(a), a.min()#another way to call

(tensor(1), tensor(1))

In [ ]:
torch.max(a), a.max()

(tensor(41), tensor(41))

In [ ]:
torch.mean(a)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#change the datatype as it throws error
torch.mean(a.type(torch.float32))

tensor(21.)

In [ ]:
#Find the sum
torch.sum(a),a.sum()

(tensor(105), tensor(105))

#finding the positional of Min and Max

In [ ]:
a


tensor([ 1, 11, 21, 31, 41])

In [ ]:
a.argmin()#here armin means argrument min value

tensor(0)

In [ ]:
a.argmax()

tensor(4)

In [ ]:
a[0]

tensor(1)

#Reshapping, stacking, squeezing and unsquezing tensors
Reshaping - rehsapes the input to define shape

staching - combine multiple tensors on tip each other(vstak) and (hstack) for side by side

view- to view of an uninput tensorsof certain shape but to keep the same memory as original tensor

squeeze: to remove the 1 dimensions from tensor
unsqueeze: to add the 1 dimension in the tensor
permute: return a view of the input with dimension permuted(swapped)in a certain way


In [ ]:
import torch
b = torch.arange(1, 9)
b, b.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [ ]:
# Reshapping

b_resh = b.reshape(1,8) # this will add the tensor to inside the single dimension which is "1" and you will see [] inside it
b_resh, b_resh.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 8]))

In [ ]:
# Reshapping

b_resh = b.reshape(4,2) # this will add the tensor to inside the single dimension which is "2" and you will see [] inside it
b_resh, b_resh.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 torch.Size([4, 2]))

In [ ]:
#change the view
y = b.view(1,8) #here we are calling the b tensor which will share the original value with y
y,


(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]),)

In [ ]:
#changing the y will change the b vlaues in the tensor as it share the original values
y[:,0]=8
y, b

(tensor([[8, 2, 3, 4, 5, 6, 7, 8]]), tensor([8, 2, 3, 4, 5, 6, 7, 8]))

In [ ]:
# Start stacking tensor on top of each other
x_stack = torch.stack([y,y,y,y],dim=0) #try chaning the dimension to dim=0/dim=1
x_stack

tensor([[[8, 2, 3, 4, 5, 6, 7, 8]],

        [[8, 2, 3, 4, 5, 6, 7, 8]],

        [[8, 2, 3, 4, 5, 6, 7, 8]],

        [[8, 2, 3, 4, 5, 6, 7, 8]]])

In [ ]:

abc = torch.arange(1,12)
abc

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
abc.shape

torch.Size([11])

In [ ]:
#torch reshape again
ab = abc.reshape(1,11)
ab, ab.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]), torch.Size([1, 11]))

In [ ]:
#torch squeeze

ab.squeeze() # this will squeeze and remove the one dimension

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
ab.squeeze().shape #here we can see the single dimesnion is removed

torch.Size([11])

In [ ]:
# torch unsqueeze()- it will add the single dimension to the tensor
print(f"previous target:{ab}")
print(f"previous shape:{ab.shape}")


#add an extra dimension with unsqueeze
unsqueezed = ab.unsqueeze(dim=0)
print(f"new tensor:{unsqueezed}")
print(f"new shape:{unsqueezed.shape}")


previous target:tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
previous shape:torch.Size([1, 11])
new tensor:tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]])
new shape:torch.Size([1, 1, 11])


In [ ]:
#torch.permute - rearranges the dimension of a traget tensor
x_original = torch.rand(size=(245,245,3))#[height,width, color channels]
x_original

 #permute the original tensor to rearrange the axis (or dim)
x_permuted = x_original.permute(2,0,1) #this will shift the axis 2->1, 0->1, 1->2

print(f"previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

previous shape:torch.Size([245, 245, 3])
New shape:torch.Size([3, 245, 245])


In [ ]:
x_original[0,0,:] #this will print the original values from 0,0 that what explains to me

tensor([0.9982, 0.3522, 0.1763])

In [ ]:
x_original[1,0,0]= 1234 #here we are chaning the values inside the original value index and it will change for permuted value too
x_original[1,0,0],x_permuted[1,0,0]

(tensor(1234.), tensor(0.3522))

#Indexing(selecting data from the tensors)
Indexing with Pytorch is similar to indexing with Numpy


In [ ]:
# create a tensor
import torch
x = torch.arange(1,17).reshape(1,4,4)#for reshape it looks like 1*4*4=16 and for arage it will 1 to 8 values
x, x.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]]]),
 torch.Size([1, 4, 4]))

In [ ]:
#let the index on new tensor
x[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [ ]:
# now will index on middle bracket
x[0][0]

tensor([1, 2, 3, 4])

In [ ]:
# let's index with last bracket which is last dimension

x[0][3]

tensor([13, 14, 15, 16])

In [ ]:
# let's index with first dimenion

x[0][0][0]

tensor(1)

In [ ]:
# you can also use":" to select all the target dimension
x[:,0]

tensor([[1, 2, 3, 4]])

In [ ]:
#get all the values of 0th and 1st dimenstion but only index 1 of 2nd dimension
x[:,:,2]

tensor([[ 3,  7, 11, 15]])

In [ ]:
#get all values of the 0 dimension means whole tensor but only the 1 index which is"[]" valu itself  of 1st and 2nd Dimension
x[:,1,1]

tensor([6])

In [ ]:
x[0,0,:]

tensor([1, 2, 3, 4])

In [ ]:
#practic
x[:,3,3]

tensor([16])

In [ ]:
x[0,2,:] # this will print whole line

tensor([ 9, 10, 11, 12])

#Pytorch tensors and Numpy


- Data in NumPy, want in Pytorch tensor -> torch.from_numpy(ndarray)
- PyTorch tensor-> NumPy-> torch.Tensor.numpy()

In [ ]:
#Numpy array to tensor
import torch
import numpy as np

array  = np.arange(1.0,9.0) #this is numpy
tensorr = torch.from_numpy(array) #WARNING:this is Tensor for torch and also Pytorch is uses the default data type from NumPy method you will see example below
array, tensorr


(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
array.dtype #see in there the dataType is float64

dtype('float64')

In [ ]:
torch.arange(1.0,8.0).dtype # in there the default is float32

torch.float32

In [ ]:
#change the value of array, for numPy
array = array + 1
array, tensorr # and this will not change the vlaue of tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy array

tensor = torch.zeros(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor #this will set the default dataType tensor to Numpy

(tensor([0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32))

In [ ]:
#change the value of tensor

tensor  = tensor+1 # this will add 1 to the tensor
tensor, numpy_tensor # and for numpy it will not add and stays default and they don't share memory

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32))

In [ ]:
#Reproducibility(Take random out of random)

torch.rand(4,4)

tensor([[0.8451, 0.2789, 0.9128, 0.8407],
        [0.2987, 0.6086, 0.6186, 0.0270],
        [0.7477, 0.5992, 0.9014, 0.9072],
        [0.3032, 0.6945, 0.7378, 0.8197]])

In [ ]:
import torch
#create two random tensors
random_A =torch.rand(3,4)
random_B =torch.rand(3,4)
print(random_A)
print(random_B)

tensor([[0.3721, 0.5095, 0.3054, 0.9242],
        [0.0402, 0.5463, 0.8601, 0.7073],
        [0.7152, 0.7176, 0.4592, 0.0208]])
tensor([[0.4388, 0.5160, 0.4914, 0.2481],
        [0.4253, 0.9480, 0.5293, 0.1087],
        [0.1701, 0.5207, 0.2554, 0.1961]])


In [ ]:
#comparing too tensor
random_A == random_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
#here we can set to tensor output would be same if we set the values indiviually
# also read reporducibility document in the pytorch
import torch

tes = 15
torch.manual_seed(tes)

random_c = torch.rand(3,4)
torch.manual_seed(tes) #this should always after the torch.rand
random_d = torch.rand(3,4)
torch.manual_seed(tes) #this should always after the torch.rand

print(random_c)
print(random_d)

tensor([[0.2973, 0.2766, 0.7974, 0.3869],
        [0.9170, 0.4125, 0.5538, 0.5646],
        [0.5026, 0.2206, 0.6801, 0.3880]])
tensor([[0.2973, 0.2766, 0.7974, 0.3869],
        [0.9170, 0.4125, 0.5538, 0.5646],
        [0.5026, 0.2206, 0.6801, 0.3880]])


#Tensor and Pytorch objects on the GPU
#types of GPU and work flow
1.Google colab
2. USe own gpu - Timdettmers search on and the info for 2024 deep learning GPU
3. could computing - GCp, AWS, Azure

In [ ]:
!nvidia-smi

Sat Jul 27 20:03:10 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#check for GPU access in Pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

In [ ]:
#putting tensors(models) on the gpu
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to GPU
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#IF tensor is on GPU, can't transform it to NumPy
#moving tensor back to CPU
tensor_gpu.numpy(0)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#fix the issue GPU tensor with numPy issue, we can first set the CPU
tensorBack_cpu = tensor_gpu.cpu().numpy()
tensorBack_cpu

array([1, 2, 3])