<a href="https://colab.research.google.com/github/harsh24895/pyTorch/blob/main/NewNote.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("ejes")



ejes


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


#introduction to tensors
Creating Tensor

In [ ]:
import torch
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt



print(torch.__version__)

#Scalar
scalar = torch.tensor(7)
scalar

2.3.0+cu121


tensor(7)

Pytorch tensors are created using torch.Tensor()

In [ ]:
import torch
#Scalar
scalar = torch.tensor(7);
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get the tensor as an int value
scalar.item()

7

In [ ]:
#vector
import torch
vector = torch.tensor([1, 1])
vector

tensor([1, 1])

In [ ]:
#vector dimension
vector.ndim

1

In [ ]:
#vector for shape
vector.shape

torch.Size([2])

In [ ]:
#MATRIX all the things are call with the torch.tensor even vector, scalar and Matrix

MATRIX  = torch.tensor([[1,3],
                        [9,4]])
MATRIX

tensor([[1, 3],
        [9, 4]])

In [ ]:
#shape of matrix
MATRIX.shape


torch.Size([2, 2])

In [ ]:
#matrix dimension
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 3])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [ ]:
TENSOR.shape
#here the 1 is from the whole index []
# second 3 is from the three index
#third 3 is from the 3 input in the index[]

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR = torch.tensor([[[[1,2,3],[2,3,4],[3,4,5]]]])
TENSOR.shape

torch.Size([1, 1, 3, 3])

#Random Tensors

In [ ]:
#Create a random tensor of size (2,4)
random_Tensor = torch.rand(2,4)
random_Tensor

tensor([[0.5119, 0.8268, 0.5360, 0.4931],
        [0.2515, 0.9545, 0.5909, 0.9945]])

In [ ]:
random_Tensor.ndim

2

In [ ]:
random_Tensor.shape

torch.Size([2, 4])

Create a random tensor with similar shape to an image  tensor

In [ ]:
random_image_size = torch.rand(size=(244,244,5)) #height, width, colour channels(R,G,B)
#also colour channels will switch first or last in the index().


random_image_size.shape , random_image_size.ndim

(torch.Size([244, 244, 5]), 3)

#Zero and ones

In [ ]:
import torch
#Create a tensor of all zeros
zero = torch.zeros(size=(2,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# tensor of ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype # this the default data type

torch.float32

In [ ]:
zero.dtype #expizitlity define the dataType

torch.float32

#Creating a range of Tensors and Tensors-like

In [ ]:
import torch
#use torch.range()
tt = torch.arange(0,5) #use the arange() instead of range() as the range is been in consistant in the python
tt

tensor([0, 1, 2, 3, 4])

In [ ]:
#Creating tensors zeros like
tenZeros = torch.zeros_like(tt)
tenZeros

tensor([0, 0, 0, 0, 0])

#TensoDataType

Note: We gonna get more error in datatypes with pytorch and deep learning
1. tensor not right datatype
2. tensor not right shape
3. tensor not right device

In [ ]:
#Float Datatype
float_t = torch.tensor([5.0,6.0,8.0],
                       dtype=None,# datatype that you can set in the tensor(ex: float32 or float16 or float64)
                       device=None, #  the default CPU and we can change to GPU(cuda)
                       requires_grad=False)# whether or not to track gradients with this tensors operations

float_t


tensor([5., 6., 8.])

In [ ]:
float_t.dtype

torch.float32

In [ ]:
#Convert the datatype to float32 default to float 16
float_16 = float_t.type(torch.float16)
float_16

tensor([5., 6., 8.], dtype=torch.float16)

In [ ]:
#even we can multiply the tensor
float_16*float_t

tensor([25., 36., 64.])

In [ ]:
#int32 to float multiply
int_32_tensor = torch.tensor([6,9,8], dtype=torch.int32)
int_32_tensor

tensor([6, 9, 8], dtype=torch.int32)

In [ ]:
int_32_tensor*float_16

tensor([30., 54., 64.], dtype=torch.float16)

#Getting information from the tensor
1.tensor not right datatype #to get the tensor information use tensor.dtype
2.tensor not right shape #to get the tensor information use tensor.shape
3.tensor not right device #to get the tensor information use tensor.device

In [ ]:
some = torch.rand(3,5)
some

tensor([[0.4684, 0.8698, 0.0595, 0.3105, 0.7077],
        [0.2095, 0.1834, 0.0539, 0.2052, 0.4716],
        [0.7746, 0.1597, 0.7539, 0.3472, 0.2999]])

In [ ]:
some.size(),  #this need to be in () if we need to call the size() menthod
some.shape #this doesn't required the () as this has a attribute

torch.Size([3, 5])

In [ ]:
#find the details of some tensor
print(some)
print(f"Datatype of tensor:{some.dtype}")
print(f"Shape of the tensor:{some.shape}")
print(f"Device od the tensor:{some.device}")

tensor([[0.4684, 0.8698, 0.0595, 0.3105, 0.7077],
        [0.2095, 0.1834, 0.0539, 0.2052, 0.4716],
        [0.7746, 0.1597, 0.7539, 0.3472, 0.2999]])
Datatype of tensor:torch.float32
Shape of the tensor:torch.Size([3, 5])
Device od the tensor:cpu


In [ ]:
#manipulating the tensors add, sub, multi, division
import torch
tensor = torch.tensor([4,5,6])
tensor +5

tensor([ 9, 10, 11])

In [ ]:
tensor -10

tensor([-6, -5, -4])

In [ ]:
#Using the inbuilt function in the tensor

torch.add(tensor,10)

tensor([14, 15, 16])

In [ ]:
#sub using inbuilt function
torch.sub(tensor,5)

tensor([-1,  0,  1])

#Matrix multiplication

Note: we can use the @ or matmul for the multiplication

#Make sure the two rules 1. inner dimmensions should match
ex: 1. (4,2) @(4,2) this will throw the error as the inner dimension is not mathcing
2. (4,2)@(2,4) this will work as their inner dimension matches
3.(2,4)@(4,2)this will work too

#2. the matrix has  the shape of outer dimension
1.(2,3)@(3,2) it will work and shows (2,2)

2.(4,5)@(5,4) - >(4,4)

In [ ]:
#Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals:{tensor * tensor}")

tensor([4, 5, 6]) * tensor([4, 5, 6])
Equals:tensor([16, 25, 36])


In [ ]:
#matix multiplication

torch.matmul(tensor, tensor) #vector version instead of for loop

tensor(77)

In [ ]:
#how it works with multiplication
4*4+5*5+6*6


77

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor(77)
CPU times: user 334 µs, sys: 1.09 ms, total: 1.42 ms
Wall time: 1.95 ms


In [ ]:
#another way to multipy the tensor
tensor @ tensor


tensor(77)

In [ ]:
#shapes of matrix multiplication

tensor1 = torch.tensor([[2,5],
                       [3,6],
                       [5,4]])

tensor2 = torch.tensor([[5,4],
                       [7,2],
                       [8,9]])

torch.mm(tensor1,tensor2)#.mm stands for matmul mm is a short form of matmul



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

# to fix the tensor we will use transpose using the T.


In [ ]:
tensor2.shape

torch.Size([3, 2])

In [ ]:
#here is the ex using the T
tensor2.T, tensor2.T.shape

(tensor([[5, 7, 8],
         [4, 2, 9]]),
 torch.Size([2, 3]))

In [ ]:
# now using tensor2.T we will multipy the matrix
# as we transform tensor2.T not the tensor1. This is eligible with the rule 1
# rule 1 is inner dimension should match so for our examples
# the tensor 1 has dimension of (3,2) and we transpose the tensor2 to (2,3) so this will work without any issue

torch.mm(tensor1,tensor2.T)#.mm stands for matmul mm is a short form of matmul



tensor([[30, 24, 61],
        [39, 33, 78],
        [41, 43, 76]])

In [ ]:
# here we are doing the outer dimmension example
# we will set the (4,3)matrix to match with rule 2
tensor3 = torch.tensor([[5,6,5],
                       [4,5,7],
                       [0,0,8],
                        [2,5,8]])
tensor4 = torch.tensor([[3,6,2],
                       [1,1,1],
                       [3,8,4],
                        [4,7,8]])

In [ ]:
torch.mm(tensor3, tensor4)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [ ]:
tensor3.T

tensor([[5, 4, 0, 2],
        [6, 5, 0, 5],
        [5, 7, 8, 8]])

In [ ]:
tensor3.T.shape

torch.Size([3, 4])

In [ ]:
torch.mm(tensor3.T, tensor4)

tensor([[ 27,  48,  30],
        [ 43,  76,  57],
        [ 78, 157, 113]])

#Finding the min,max,sum(tesnor aggregation)

In [ ]:
#Create a tensor
a = torch.arange(1,50,10)
a

tensor([ 1, 11, 21, 31, 41])

In [ ]:
torch.min(a), a.min()#another way to call

(tensor(1), tensor(1))

In [ ]:
torch.max(a), a.max()

(tensor(41), tensor(41))

In [ ]:
torch.mean(a)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#change the datatype as it throws error
torch.mean(a.type(torch.float32))

tensor(21.)

In [ ]:
#Find the sum
torch.sum(a),a.sum()

(tensor(105), tensor(105))

#finding the positional of Min and Max

In [ ]:
a


tensor([ 1, 11, 21, 31, 41])

In [ ]:
a.argmin()#here armin means argrument min value

tensor(0)

In [ ]:
a.argmax()

tensor(4)

In [ ]:
a[0]

tensor(1)

#Reshapping, stacking, squeezing and unsquezing tensors
Reshaping - rehsapes the input to define shape

staching - combine multiple tensors on tip each other(vstak) and (hstack) for side by side

view- to view of an uninput tensorsof certain shape but to keep the same memory as original tensor

squeeze: to remove the 1 dimensions from tensor
unsqueeze: to add the 1 dimension in the tensor
permute: return a view of the input with dimension permuted(swapped)in a certain way


In [ ]:
import torch
b = torch.arange(1, 9)
b, b.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [ ]:
# Reshapping

b_resh = b.reshape(1,8) # this will add the tensor to inside the single dimension which is "1" and you will see [] inside it
b_resh, b_resh.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 8]))

In [ ]:
# Reshapping

b_resh = b.reshape(4,2) # this will add the tensor to inside the single dimension which is "2" and you will see [] inside it
b_resh, b_resh.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 torch.Size([4, 2]))

In [ ]:
#change the view
y = b.view(1,8) #here we are calling the b tensor which will share the original value with y
y,


(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]),)

In [ ]:
#changing the y will change the b vlaues in the tensor as it share the original values
y[:,0]=8
y

tensor([[8, 2, 3, 4, 5, 6, 7, 8]])