In [2]:
print("ejes")



ejes


In [3]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


#introduction to tensors
Creating Tensor

In [4]:
import torch
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt



print(torch.__version__)

#Scalar
scalar = torch.tensor(7)
scalar

2.3.0+cu121


tensor(7)

Pytorch tensors are created using torch.Tensor()

In [5]:
import torch
#Scalar
scalar = torch.tensor(7);
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#get the tensor as an int value
scalar.item()

7

In [8]:
#vector
import torch
vector = torch.tensor([1, 1])
vector

tensor([1, 1])

In [9]:
#vector dimension
vector.ndim

1

In [10]:
#vector for shape
vector.shape

torch.Size([2])

In [11]:
#MATRIX all the things are call with the torch.tensor even vector, scalar and Matrix

MATRIX  = torch.tensor([[1,3],
                        [9,4]])
MATRIX

tensor([[1, 3],
        [9, 4]])

In [12]:
#shape of matrix
MATRIX.shape


torch.Size([2, 2])

In [13]:
#matrix dimension
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([1, 3])

In [15]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],[2,3,4],[3,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [16]:
TENSOR.shape
#here the 1 is from the whole index []
# second 3 is from the three index
#third 3 is from the 3 input in the index[]

torch.Size([1, 3, 3])

In [17]:
TENSOR.ndim


3

In [18]:
TENSOR = torch.tensor([[[[1,2,3],[2,3,4],[3,4,5]]]])
TENSOR.shape

torch.Size([1, 1, 3, 3])

#Random Tensors

In [19]:
#Create a random tensor of size (2,4)
random_Tensor = torch.rand(2,4)
random_Tensor

tensor([[0.9926, 0.0960, 0.4527, 0.1839],
        [0.3866, 0.9813, 0.5229, 0.3978]])

In [20]:
random_Tensor.ndim

2

In [21]:
random_Tensor.shape

torch.Size([2, 4])

Create a random tensor with similar shape to an image  tensor

In [22]:
random_image_size = torch.rand(size=(244,244,5)) #height, width, colour channels(R,G,B)
#also colour channels will switch first or last in the index().


random_image_size.shape , random_image_size.ndim

(torch.Size([244, 244, 5]), 3)

#Zero and ones

In [23]:
import torch
#Create a tensor of all zeros
zero = torch.zeros(size=(2,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# tensor of ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype # this the default data type

torch.float32

In [26]:
zero.dtype #expizitlity define the dataType

torch.float32

#Creating a range of Tensors and Tensors-like

In [27]:
import torch
#use torch.range()
tt = torch.arange(0,5) #use the arange() instead of range() as the range is been in consistant in the python
tt

tensor([0, 1, 2, 3, 4])

In [28]:
#Creating tensors zeros like
tenZeros = torch.zeros_like(tt)
tenZeros

tensor([0, 0, 0, 0, 0])

#TensoDataType

Note: We gonna get more error in datatypes with pytorch and deep learning
1. tensor not right datatype
2. tensor not right shape
3. tensor not right device

In [29]:
#Float Datatype
float_t = torch.tensor([5.0,6.0,8.0],
                       dtype=None,# datatype that you can set in the tensor(ex: float32 or float16 or float64)
                       device=None, #  the default CPU and we can change to GPU(cuda)
                       requires_grad=False)# whether or not to track gradients with this tensors operations

float_t


tensor([5., 6., 8.])

In [30]:
float_t.dtype

torch.float32

In [31]:
#Convert the datatype to float32 default to float 16
float_16 = float_t.type(torch.float16)
float_16

tensor([5., 6., 8.], dtype=torch.float16)

In [32]:
#even we can multiply the tensor
float_16*float_t

tensor([25., 36., 64.])

In [33]:
#int32 to float multiply
int_32_tensor = torch.tensor([6,9,8], dtype=torch.int32)
int_32_tensor

tensor([6, 9, 8], dtype=torch.int32)

In [34]:
int_32_tensor*float_16

tensor([30., 54., 64.], dtype=torch.float16)

#Getting information from the tensor
1.tensor not right datatype #to get the tensor information use tensor.dtype
2.tensor not right shape #to get the tensor information use tensor.shape
3.tensor not right device #to get the tensor information use tensor.device

In [35]:
some = torch.rand(3,5)
some

tensor([[0.5068, 0.4706, 0.7992, 0.7876, 0.8895],
        [0.9580, 0.9090, 0.2418, 0.4965, 0.9761],
        [0.0773, 0.1334, 0.5440, 0.0897, 0.1708]])

In [36]:
some.size(),  #this need to be in () if we need to call the size() menthod
some.shape #this doesn't required the () as this has a attribute

torch.Size([3, 5])

In [37]:
#find the details of some tensor
print(some)
print(f"Datatype of tensor:{some.dtype}")
print(f"Shape of the tensor:{some.shape}")
print(f"Device od the tensor:{some.device}")

tensor([[0.5068, 0.4706, 0.7992, 0.7876, 0.8895],
        [0.9580, 0.9090, 0.2418, 0.4965, 0.9761],
        [0.0773, 0.1334, 0.5440, 0.0897, 0.1708]])
Datatype of tensor:torch.float32
Shape of the tensor:torch.Size([3, 5])
Device od the tensor:cpu


In [38]:
#manipulating the tensors add, sub, multi, division
import torch
tensor = torch.tensor([4,5,6])
tensor +5

tensor([ 9, 10, 11])

In [39]:
tensor -10

tensor([-6, -5, -4])

In [40]:
#Using the inbuilt function in the tensor

torch.add(tensor,10)

tensor([14, 15, 16])

In [41]:
#sub using inbuilt function
torch.sub(tensor,5)

tensor([-1,  0,  1])

#Matrix multiplication

Note: we can use the @ or matmul for the multiplication

#Make sure the two rules 1. inner dimmensions should match
ex: 1. (4,2) @(4,2) this will throw the error as the inner dimension is not mathcing
2. (4,2)@(2,4) this will work as their inner dimension matches
3.(2,4)@(4,2)this will work too

#2. the matrix has  the shape of outer dimension
1.(2,3)@(3,2) it will work and shows (2,2)

2.(4,5)@(5,4) - >(4,4)

In [42]:
#Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals:{tensor * tensor}")

tensor([4, 5, 6]) * tensor([4, 5, 6])
Equals:tensor([16, 25, 36])


In [43]:
#matix multiplication

torch.matmul(tensor, tensor) #vector version instead of for loop

tensor(77)

In [44]:
#how it works with multiplication
4*4+5*5+6*6


77

In [45]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)



tensor(77)
CPU times: user 1.79 ms, sys: 136 µs, total: 1.92 ms
Wall time: 2.23 ms


In [46]:
#another way to multipy the tensor
tensor @ tensor


tensor(77)

In [48]:
#shapes of matrix multiplication

tensor1 = torch.tensor([[2,5],
                       [3,6],
                       [5,4]])

tensor2 = torch.tensor([[5,4],
                       [7,2],
                       [8,9]])

torch.mm(tensor1,tensor2)#.mm stands for matmul mm is a short form of matmul



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

# to fix the tensor we will use transpose using the T.


In [49]:
tensor2.shape

torch.Size([3, 2])

In [50]:
#here is the ex using the T
tensor2.T, tensor2.T.shape

(tensor([[5, 7, 8],
         [4, 2, 9]]),
 torch.Size([2, 3]))

In [51]:
# now using tensor2.T we will multipy the matrix
# as we transform tensor2.T not the tensor1. This is eligible with the rule 1
# rule 1 is inner dimension should match so for our examples
# the tensor 1 has dimension of (3,2) and we transpose the tensor2 to (2,3) so this will work without any issue

torch.mm(tensor1,tensor2.T)#.mm stands for matmul mm is a short form of matmul



tensor([[30, 24, 61],
        [39, 33, 78],
        [41, 43, 76]])

In [52]:
# here we are doing the outer dimmension example
# we will set the (4,3)matrix to match with rule 2
tensor3 = torch.tensor([[5,6,5],
                       [4,5,7],
                       [0,0,8],
                        [2,5,8]])
tensor4 = torch.tensor([[3,6,2],
                       [1,1,1],
                       [3,8,4],
                        [4,7,8]])

In [54]:
torch.mm(tensor3, tensor4)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 4x3)

In [55]:
tensor3.T

tensor([[5, 4, 0, 2],
        [6, 5, 0, 5],
        [5, 7, 8, 8]])

In [56]:
tensor3.T.shape

torch.Size([3, 4])

In [57]:
torch.mm(tensor3.T, tensor4)

tensor([[ 27,  48,  30],
        [ 43,  76,  57],
        [ 78, 157, 113]])

#Finding the min,max,sum(tesnor aggregation)

In [58]:
#Create a tensor
a = torch.arange(1,50,10)
a

tensor([ 1, 11, 21, 31, 41])

In [59]:
torch.min(a), a.min()#another way to call

(tensor(1), tensor(1))

In [60]:
torch.max(a), a.max()

(tensor(41), tensor(41))

In [62]:
torch.mean(a)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [63]:
#change the datatype as it throws error
torch.mean(a.type(torch.float32))

tensor(21.)

In [64]:
#Find the sum
torch.sum(a),a.sum()

(tensor(105), tensor(105))

#finding the positional of Min and Max

In [65]:
a


tensor([ 1, 11, 21, 31, 41])

In [66]:
a.argmin()#here armin means argrument min value

tensor(0)

In [67]:
a.argmax()

tensor(4)

In [68]:
a[0]

tensor(1)

#Reshapping, stacking, squeezing and unsquezing tensors
Reshaping - rehsapes the input to define shape

staching - combine multiple tensors on tip each other(vstak) and (hstack) for side by side

view- to view of an uninput tensorsof certain shape but to keep the same memory as original tensor

squeeze: to remove the 1 dimensions from tensor
unsqueeze: to add the 1 dimension in the tensor
permute: return a view of the input with dimension permuted(swapped)in a certain way


In [69]:
import torch
b = torch.arange(1, 9)
b, b.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [70]:
# Reshapping

b_resh = b.reshape(1,8) # this will add the tensor to inside the single dimension which is "1" and you will see [] inside it
b_resh, b_resh.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 8]))

In [71]:
# Reshapping

b_resh = b.reshape(4,2) # this will add the tensor to inside the single dimension which is "2" and you will see [] inside it
b_resh, b_resh.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 torch.Size([4, 2]))

In [72]:
#change the view
y = b.view(1,8) #here we are calling the b tensor which will share the original value with y
y,


(tensor([[1, 2, 3, 4, 5, 6, 7, 8]]),)

In [73]:
#changing the y will change the b vlaues in the tensor as it share the original values
y[:,0]=8
y, b

(tensor([[8, 2, 3, 4, 5, 6, 7, 8]]), tensor([8, 2, 3, 4, 5, 6, 7, 8]))

In [79]:
# Start stacking tensor on top of each other
x_stack = torch.stack([y,y,y,y],dim=0) #try chaning the dimension to dim=0/dim=1
x_stack

tensor([[[8, 2, 3, 4, 5, 6, 7, 8]],

        [[8, 2, 3, 4, 5, 6, 7, 8]],

        [[8, 2, 3, 4, 5, 6, 7, 8]],

        [[8, 2, 3, 4, 5, 6, 7, 8]]])